# Site settings
title: Noted.
email: hello@jamiesp.me
description: > # this means to ignore newlines until "baseurl:"
  Aesthetic as expression. <BR> Web development / Anthropology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

google_analytics: #GA code
